### ISSUE TITLE
deployment of releases fails

### ISSUE THREAD

**Issue by dbu** [liip/roger-q#20]
i tagged 0.0.2 but deployment fails : https://travis-ci.com/liip/roger-q/jobs/228117172

@mweibel do you have an idea why that could be happening? do you still have rights on the repo, or if not could the api key have been linked with your account?

**Comment by mweibel** [comment]
hm, travis-ci.com is the pro version while you actually use the .org version. Unsure why that URL even works? where did you get the URL from, too?
https://travis-ci.org/liip/roger-q/jobs/576705101

all good there :)

**Comment by dbu** [comment]
oh, that indeed is weird. i got that notification from the .com - maybe that is their way of marketing :grin: . found that we have both the notify hook and had roger-q in the list of things that are in travis-ci in "Installed GitHub Apps" - i removed that one, hope that fixes it.

thanks a lot for the quick help and for realizing the .com vs .org thing!
